# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Install dependencies and wget
RUN apt-get update && apt-get install -y wget

# Copy the current directory contents into the container
COPY . /app

# Install Python packages
RUN pip install "ray[serve]" transformers torch

# Command to run the application
CMD ["python", "multiple_models_demo.py"]
