apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ray-metrics
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      ray.io/node-type: head
      job: serve-multiple-models-head-svc
  endpoints:
    - port: metrics
      path: /metrics
      interval: 10s